{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "architecture",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "architecture-1.0.0-SNAPSHOT.jar",
          "url": "architecture-1.0.0-SNAPSHOT.jar",
          "size": 27944,
          "sha512": "e07f58fa4afcc4c1ee76cef41777a963f95ed0826a61e5c13751f06d69c1cd6d82460f12043b443e0fdc990a458f75c3f8cfec27aa2750c2c54a142ff15a5e56",
          "sha256": "f65f8cbddc43e3b000c2664f4454d24ed161036ff89b2afc1b2303f9b229733d",
          "sha1": "918c5284be8c5418a5045c9a7b8b25fae0798123",
          "md5": "2be5f05e8469f2f0bdb7e5b055f80d35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "architecture-1.0.0-SNAPSHOT.jar",
          "url": "architecture-1.0.0-SNAPSHOT.jar",
          "size": 27944,
          "sha512": "e07f58fa4afcc4c1ee76cef41777a963f95ed0826a61e5c13751f06d69c1cd6d82460f12043b443e0fdc990a458f75c3f8cfec27aa2750c2c54a142ff15a5e56",
          "sha256": "f65f8cbddc43e3b000c2664f4454d24ed161036ff89b2afc1b2303f9b229733d",
          "sha1": "918c5284be8c5418a5045c9a7b8b25fae0798123",
          "md5": "2be5f05e8469f2f0bdb7e5b055f80d35"
        }
      ]
    }
  ]
}
