{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "coroutines",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "coroutines-1.0.0-SNAPSHOT.jar",
          "url": "coroutines-1.0.0-SNAPSHOT.jar",
          "size": 66491,
          "sha512": "10d3e4b8ffa97d2bf15191a08fe0a4bcfbbda04f001a3c40d59b58f6612224a9281795809add6975cfcbce3719ea377d5b8b29667e250b9854fae09af4f00822",
          "sha256": "3657232242475e2600c2adc4a366e5667f7f104fa8cf0c17e4e54004d2714fca",
          "sha1": "7faaa11f13571920477cbb2b6e64a579c5793cec",
          "md5": "d423583f40dc22bd68583ec0158785d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "coroutines-1.0.0-SNAPSHOT.jar",
          "url": "coroutines-1.0.0-SNAPSHOT.jar",
          "size": 66491,
          "sha512": "10d3e4b8ffa97d2bf15191a08fe0a4bcfbbda04f001a3c40d59b58f6612224a9281795809add6975cfcbce3719ea377d5b8b29667e250b9854fae09af4f00822",
          "sha256": "3657232242475e2600c2adc4a366e5667f7f104fa8cf0c17e4e54004d2714fca",
          "sha1": "7faaa11f13571920477cbb2b6e64a579c5793cec",
          "md5": "d423583f40dc22bd68583ec0158785d7"
        }
      ]
    }
  ]
}
