{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "menu",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "menu-1.0.0-SNAPSHOT.jar",
          "url": "menu-1.0.0-SNAPSHOT.jar",
          "size": 123573,
          "sha512": "2a2aec3982fa320d641b7ab24dbc95705c19dd42e0fc17898434bbbc8d2fafcbdf25eca5c92082892943b2e294e28866d41c7c8192956bde0f47380aba5398ad",
          "sha256": "64cc724cb1e5fdf1d28ed86f5faee7f8a5e014896b24608b0b99e4ff6887eaea",
          "sha1": "ed16a36dc7c60edef6f981dcac3de2a2aae168d8",
          "md5": "7b3c744bccd88495d54720ecc9a414d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "menu-1.0.0-SNAPSHOT.jar",
          "url": "menu-1.0.0-SNAPSHOT.jar",
          "size": 123573,
          "sha512": "2a2aec3982fa320d641b7ab24dbc95705c19dd42e0fc17898434bbbc8d2fafcbdf25eca5c92082892943b2e294e28866d41c7c8192956bde0f47380aba5398ad",
          "sha256": "64cc724cb1e5fdf1d28ed86f5faee7f8a5e014896b24608b0b99e4ff6887eaea",
          "sha1": "ed16a36dc7c60edef6f981dcac3de2a2aae168d8",
          "md5": "7b3c744bccd88495d54720ecc9a414d7"
        }
      ]
    }
  ]
}
