{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "extensions",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.0.0-SNAPSHOT.jar",
          "url": "extensions-1.0.0-SNAPSHOT.jar",
          "size": 75175,
          "sha512": "2cfd3014f63223c07094c4f1c64b3afb8201af5683280e1bbca44e94f3f5a8cc6c5b903c9e04631a2dd08e597573fed236647f784876aefb96661d211020d7ba",
          "sha256": "5a9bf693941893481c4a4b9b9028ffb3ba47c926685eab8a8ed75e6bc2442483",
          "sha1": "b0f09bc0a396575cc2553a66aa5879f27fc4f942",
          "md5": "1432da3179281a6c7527e7f067b97ec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.0.0-SNAPSHOT.jar",
          "url": "extensions-1.0.0-SNAPSHOT.jar",
          "size": 75175,
          "sha512": "2cfd3014f63223c07094c4f1c64b3afb8201af5683280e1bbca44e94f3f5a8cc6c5b903c9e04631a2dd08e597573fed236647f784876aefb96661d211020d7ba",
          "sha256": "5a9bf693941893481c4a4b9b9028ffb3ba47c926685eab8a8ed75e6bc2442483",
          "sha1": "b0f09bc0a396575cc2553a66aa5879f27fc4f942",
          "md5": "1432da3179281a6c7527e7f067b97ec8"
        }
      ]
    }
  ]
}
