{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "serialization",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-1.0.0-SNAPSHOT.jar",
          "url": "serialization-1.0.0-SNAPSHOT.jar",
          "size": 63109,
          "sha512": "f96dcd93b674ef06b2a2c1597af897aef10650b0e4ce9893eb644133f285e308c35c142c7697517522f9935ed23dfb1daaf42e85ead05d58eca4ab1b55de0aca",
          "sha256": "5219c698a293c3916f6626fc095d5cecd873bc1e3aa9597b50aa51ddf1e2132a",
          "sha1": "9f5a84fb0c24063a54fde3854d171f13090c0e6c",
          "md5": "9aa4da046ec52cc3670d2ad46a82ea5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-1.0.0-SNAPSHOT.jar",
          "url": "serialization-1.0.0-SNAPSHOT.jar",
          "size": 63109,
          "sha512": "f96dcd93b674ef06b2a2c1597af897aef10650b0e4ce9893eb644133f285e308c35c142c7697517522f9935ed23dfb1daaf42e85ead05d58eca4ab1b55de0aca",
          "sha256": "5219c698a293c3916f6626fc095d5cecd873bc1e3aa9597b50aa51ddf1e2132a",
          "sha1": "9f5a84fb0c24063a54fde3854d171f13090c0e6c",
          "md5": "9aa4da046ec52cc3670d2ad46a82ea5b"
        }
      ]
    }
  ]
}
