{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "command-legacy",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "coroutines",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "command-legacy-1.0.0-SNAPSHOT.jar",
          "url": "command-legacy-1.0.0-SNAPSHOT.jar",
          "size": 85526,
          "sha512": "9408784ccfc757c12dfd3c74221ef51d684e8a49fac350d396badb948f6a80964ef2aa3a6036f2d1850af4ef47b6fd8631d90396632d5ffb49b3cacb5b585d73",
          "sha256": "ad16694ec081cd6fd00db5d4432a94d5bb3dbd255adb2f78e084aba622645d07",
          "sha1": "fbdbc2b3443379a091584806b23582869c425981",
          "md5": "53b9cfc2ba7447ae5d7b1e34f49818c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "coroutines",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "command-legacy-1.0.0-SNAPSHOT.jar",
          "url": "command-legacy-1.0.0-SNAPSHOT.jar",
          "size": 85526,
          "sha512": "9408784ccfc757c12dfd3c74221ef51d684e8a49fac350d396badb948f6a80964ef2aa3a6036f2d1850af4ef47b6fd8631d90396632d5ffb49b3cacb5b585d73",
          "sha256": "ad16694ec081cd6fd00db5d4432a94d5bb3dbd255adb2f78e084aba622645d07",
          "sha1": "fbdbc2b3443379a091584806b23582869c425981",
          "md5": "53b9cfc2ba7447ae5d7b1e34f49818c7"
        }
      ]
    }
  ]
}
