{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "scoreboard-legacy",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "url": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "size": 27170,
          "sha512": "50972d7ea7296251676f5542a1835a4902afa63a3228bf523dd10114b0e2c36aafe11e85674069449c965dab714f3d62659e4e2b84b118fa51e6b994496947fe",
          "sha256": "8d3518655c27ee0759c014b0f417fcb39a252c7163c1aa46e087abbd18c7b531",
          "sha1": "4dbdd794639ff4cc54570fc4a7955c59c1928fc8",
          "md5": "90e5939bdb7f7f83daaf32d90480c8ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "url": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "size": 27170,
          "sha512": "50972d7ea7296251676f5542a1835a4902afa63a3228bf523dd10114b0e2c36aafe11e85674069449c965dab714f3d62659e4e2b84b118fa51e6b994496947fe",
          "sha256": "8d3518655c27ee0759c014b0f417fcb39a252c7163c1aa46e087abbd18c7b531",
          "sha1": "4dbdd794639ff4cc54570fc4a7955c59c1928fc8",
          "md5": "90e5939bdb7f7f83daaf32d90480c8ed"
        }
      ]
    }
  ]
}
