{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "scoreboard-legacy",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "url": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "size": 27170,
          "sha512": "8ebabe2d813a1ed46dae52715e9139fbe42d3d975332a5c920a3cd6f03e879dc8d97f3e27b8bcc984d882a84c81d3ee4ad71bae8fcdb034e253f09d796b5061f",
          "sha256": "0097d95596a391e3a9cebd6883d16afb458fc99d28528b9701193f3bcbd31864",
          "sha1": "9efed8352e23fe5649ecfc7dfd3588b65eae0e13",
          "md5": "943cbbdcf51c1aa598da66a4eaf761cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "extensions",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "url": "scoreboard-legacy-1.0.0-SNAPSHOT.jar",
          "size": 27170,
          "sha512": "8ebabe2d813a1ed46dae52715e9139fbe42d3d975332a5c920a3cd6f03e879dc8d97f3e27b8bcc984d882a84c81d3ee4ad71bae8fcdb034e253f09d796b5061f",
          "sha256": "0097d95596a391e3a9cebd6883d16afb458fc99d28528b9701193f3bcbd31864",
          "sha1": "9efed8352e23fe5649ecfc7dfd3588b65eae0e13",
          "md5": "943cbbdcf51c1aa598da66a4eaf761cd"
        }
      ]
    }
  ]
}
