{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.devsrsouza.kotlinbukkitapi",
    "module": "exposed",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "exposed-1.0.0-SNAPSHOT.jar",
          "url": "exposed-1.0.0-SNAPSHOT.jar",
          "size": 115061,
          "sha512": "1f32dfac2c526f086f3d8f639036bf2b7eeeedb5c1aae5316922f962b61fbbbe579ee941b676017ddd66980c322aedb715b54501a75bb681fd9fc8651eb8869a",
          "sha256": "775e29f5aa63625328eeb330d237b283e49829d435db853665d869579990b139",
          "sha1": "52284871766946928120c3271de430198758d6da",
          "md5": "e7b71a502bb27aad6060fcb4bafa8a86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.40.1"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-dao",
          "version": {
            "requires": "0.40.1"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "architecture",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "br.com.devsrsouza.kotlinbukkitapi",
          "module": "utility",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "exposed-1.0.0-SNAPSHOT.jar",
          "url": "exposed-1.0.0-SNAPSHOT.jar",
          "size": 115061,
          "sha512": "1f32dfac2c526f086f3d8f639036bf2b7eeeedb5c1aae5316922f962b61fbbbe579ee941b676017ddd66980c322aedb715b54501a75bb681fd9fc8651eb8869a",
          "sha256": "775e29f5aa63625328eeb330d237b283e49829d435db853665d869579990b139",
          "sha1": "52284871766946928120c3271de430198758d6da",
          "md5": "e7b71a502bb27aad6060fcb4bafa8a86"
        }
      ]
    }
  ]
}
